plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}
android {
    namespace 'ir.tajeritools.factorkhan'
    compileSdk 35
    defaultConfig {
        applicationId "ir.tajeritools.factorkhan"
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName "6.4.0"
    }
    buildFeatures { buildConfig true }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
    packaging {
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}', 'META-INF/DEPENDENCIES'] }
    }
}
dependencies {
    implementation 'androidx.core:core-ktx:1.16.0'
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity-ktx:1.10.1'
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
    implementation 'cz.adaptech.tesseract4android:tesseract4android:4.9.0'
    implementation 'com.microsoft.onnxruntime:onnxruntime-android:1.21.1'
}
